version: "3.9"

services:
  mysql:
    build: ./mysql
    env_file: ./mysql/.env
    container_name: mysql_container
    volumes:
      - ./mysq:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
