name: frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock
      - name: Install node_modules
        run: yarn install --check-files --frozen-lockfile --non-interactive
        working-directory: ./frontend
      - name: Cache node_modules
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-v${{ matrix.node-version }}-node-modules-frontend-yarn.lock

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: ./frontend
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock
      - name: Restore node_modules
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-v${{ matrix.node-version }}-node-modules-frontend-yarn.lock
      - name: Check prettier format
        run: yarn format:check
      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: ./frontend
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock
      - name: Restore node_modules
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node-v${{ matrix.node-version }}-node-modules-frontend-yarn.lock
      - name: Test
        run: |
          yarn type-check
          yarn test
